export const API_BASE_URL =
  import.meta.env.VITE_API_URL || "http://localhost:8000";

export const NG_STATES = [
  { id: "lagos", name: "Lagos" },
  { id: "abuja", name: "Abuja (FCT)" },
  { id: "rivers", name: "Rivers (Port Harcourt)" },
  { id: "oyo", name: "Oyo (Ibadan)" },
  { id: "enugu", name: "Enugu" },
  { id: "kano", name: "Kano" },
  { id: "kaduna", name: "Kaduna" },
  { id: "delta", name: "Delta (Warri/Asaba)" },
  { id: "edo", name: "Edo (Benin City)" },
  { id: "ogun", name: "Ogun (Abeokuta)" },
  { id: "anambra", name: "Anambra (Awka/Onitsha)" },
  { id: "cross_river", name: "Cross River (Calabar)" },
  { id: "akwa_ibom", name: "Akwa Ibom (Uyo)" },
  { id: "imo", name: "Imo (Owerri)" },
  { id: "abia", name: "Abia (Aba/Umuahia)" },
  { id: "kwara", name: "Kwara (Ilorin)" },
  { id: "osun", name: "Osun (Osogbo)" },
  { id: "ondo", name: "Ondo (Akure)" },
  { id: "ekiti", name: "Ekiti (Ado Ekiti)" },
  { id: "plateau", name: "Plateau (Jos)" },
  { id: "benue", name: "Benue (Makurdi)" },
  { id: "adamawa", name: "Adamawa (Yola)" },
  { id: "bauchi", name: "Bauchi" },
  { id: "bayelsa", name: "Bayelsa (Yenagoa)" },
  { id: "borno", name: "Borno (Maiduguri)" },
  { id: "ebonyi", name: "Ebonyi (Abakaliki)" },
  { id: "gombe", name: "Gombe" },
  { id: "jigawa", name: "Jigawa (Dutse)" },
  { id: "katsina", name: "Katsina" },
  { id: "kebbi", name: "Kebbi (Birnin Kebbi)" },
  { id: "kogi", name: "Kogi (Lokoja)" },
  { id: "nasarawa", name: "Nasarawa (Lafia)" },
  { id: "niger", name: "Niger (Minna)" },
  { id: "sokoto", name: "Sokoto" },
  { id: "taraba", name: "Taraba (Jalingo)" },
  { id: "yobe", name: "Yobe (Damaturu)" },
  { id: "zamfara", name: "Zamfara (Gusau)" },
  { id: "virtual", name: "Virtual / Remote" },
];

export const CATEGORIES = [
  { id: "tech", name: "Tech & Developer" },
  { id: "hackathon", name: "Hackathons" },
  { id: "product", name: "Product / Design" },
  { id: "lifestyle", name: "Lifestyle & Social" },
];
